language: ruby
cache: bundler
rvm:
  - 2.5

_GEM_INSTALL: &GEM_INSTALL
  - echo "_GEM_INSTALL"
  - gem install bundler
  - bundle install
  - bundle exec jekyll build --config=_config.yml,_config_production.yml

jobs:
  include:
    - name: Links validation
      script:
        - bundle exec htmlproofer ./_site --allow-hash-href
      install:
        - *GEM_INSTALL

    - name: Page validation
      script:
        - bundle exec jekyll validate
      install:
        - *GEM_INSTALL

    - name: Push pages to Algolia
      if: branch = master
      script:
        - bundle exec jekyll algolia --config=_config.yml,algolia_config/_marketplace_dev.yml
        - bundle exec jekyll algolia --config=_config.yml,algolia_config/_marketplace_user.yml
      install:
        - *GEM_INSTALL
