version: "202311.0"

repository: spryker/spryker-docs

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Spryker Documentation
# this appears on the top navigation bar next to the home button

site_title: Spryker Documentation
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: Spryker
# this appears in the footer

github_editme_path: spryker/spryker-docs/blob/master/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

google_analytics: "G-CPJX4XMTD1"
# if you have google-analytics ID, put it in. if not, edit this value to blank.

feedback_disable: true

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .idea/
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - static.json
  - node_modules/
  - vendor
  - node_modules
  - package.json
  - package-lock.json
  - gulpfile.js
  - redirect.html
  - docs/scos/dev/drafts-dev/
  - docs/scos/dev/developers-corner/

# these are the files and directories that jekyll will exclude from the build

highlighter: rouge
# library used for syntax highlighting

markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

plugins:
  - jekyll-last-modified-at
  - jekyll-include-cache

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      topnav: topnav
  -
    scope:
      path: "docs/"
    values:
      feed: true
  -
    scope:
      path: "docs/scos"
    values:
      product: "scos"
  -
    scope:
      path: "docs/scos/dev"
    values:
      sidebar: "scos_dev_sidebar"
      role: "dev"
  -
    scope:
      path: "docs/scos/user"
    values:
      sidebar: "scos_user_sidebar"
      role: "user"
  -
     scope:
       path: "docs/sdk"
     values:
       product: "sdk"
  -
     scope:
       path: "docs/sdk/dev"
     values:
       sidebar: "sdk_dev_sidebar"
       role: "dev"
  -
    scope:
      path: "docs/ca"
    values:
      product: "ca"
  -
    scope:
      path: "docs/ca/dev"
    values:
      sidebar: "ca_dev_sidebar"
      role: "dev"
  -
    scope:
      path: "docs/acp"
    values:
      product: "acp"
  -
    scope:
      path: "docs/acp/user"
    values:
      sidebar: "acp_user_sidebar"
      role: "user"
  -
     scope:
       path: "docs/scu"
     values:
       product: "scu"
  -
     scope:
       path: "docs/scu/dev"
     values:
       sidebar: "scu_dev_sidebar"
       role: "dev"
  -
     scope:
       path: "docs/pbc"
     values:
       product: "pbc"
  -
    scope:
      path: "docs/pbc/all"
    values:
      sidebar: "pbc_all_sidebar"
      role: "all"

versions:
  '202204.0': '202204.0'
  '202212.0': '202212.0'
  '202307.0': '202307.0'
  '202311.0': '202311.0'

# versioned categories - these must match corresponding directories
versioned_categories:
  scos:
    user:
      - features
      - back-office-user-guides
      - technology-partners
      - shop-user-guides
      - overview-of-features
    dev:
      - feature-walkthroughs
      - feature-integration-guides
      - data-import
      - data-export
      - glue-api-guides
      - technology-partner-integration-guides
      - the-docker-sdk
      - migration-and-integration
      - legacy-demoshop
      - technology-partner-guides
      - devops-migration-guides
      - system-requirements
      - front-end-development
  pbc:
    all:
      - back-office
      - cart-and-checkout
      - carrier-management
      - content-management-system
      - customer-relationship-management
      - data-exchange
      - discount-management
      - dynamic-multistore
      - emails
      - gift-cards
      - identity-access-management
      - merchant-management
      - miscellaneous
      - offer-management
      - order-management-system
      - price-management
      - payment-service-provider
      - product-information-management
      - product-relationship-management
      - push-notification
      - return-management
      - ratings-reviews
      - request-for-quote
      - search
      - service-point-management
      - shopping-list-and-wishlist
      - tax-management
      - user-management
      - warehouse-management-system
      - warehouse-picking



# these are defaults used for the front matter for these file types

sidebars:
  - ca_dev_sidebar
  - scos_dev_sidebar
  - scos_user_sidebar
  - sdk_dev_sidebar
  - acp_user_sidebar
  - scu_dev_sidebar
  - pbc_all_sidebar

description: "Spryker documentation center."
# the description is used in the feed.xml file

# needed for sitemap.xml file only
# url: http://idratherbewriting.com
# baseurl: /documentation-theme-jekyll


github: [metadata]

search: algolia

algolia:
  application_id: 'IBBSSFT6M1'
  search_only_api_key: '296ac9c40fa95441b2d89d1fd8395bb4'
  max_record_size: 20000
  indices:
    - name: 'pbc_all'
      title: 'Packaged Business Capabilities'
    - name: 'scos_user'
      title: 'SCOS User'
    - name: 'scos_dev'
      title: 'SCOS Developer'
    - name: 'sdk_dev'
      title: 'SDK Developer'
    - name: 'ca_dev'
      title: 'Cloud administration'
    - name: 'acp_user'
      title: 'ACP User'
    - name: 'scu_dev'
      title: 'SCU Developer'
sass:
    sass_dir: css
    style: compressed
    sourcemap: never

last-modified-at:
  date-format: '%Y%m%dT%H%M'

redirect_from:
  json: false

form_endpoints:
  feedback: 'https://formspree.io/f/xdoboyro'
